"""Application commands package."""

# Base class - stays at root level
from .command_handler_base import CommandHandlerBase

# Lab commands
from .lab import (
    ControlLabCommand,
    ControlLabCommandHandler,
    DeleteLabCommand,
    DeleteLabCommandHandler,
    DownloadLabCommand,
    DownloadLabCommandHandler,
    ImportLabCommand,
    ImportLabCommandHandler,
    LabAction,
)

# Settings commands
from .settings import UpdateSystemSettingsCommand, UpdateSystemSettingsCommandHandler

# Task commands
from .task import (
    CreateTaskCommand,
    CreateTaskCommandHandler,
    DeleteTaskCommand,
    DeleteTaskCommandHandler,
    UpdateTaskCommand,
    UpdateTaskCommandHandler,
)

# Worker commands
from .worker import (
    BulkImportCMLWorkersCommand,
    BulkImportCMLWorkersCommandHandler,
    BulkImportResult,
    BulkSyncResult,
    BulkSyncWorkerCMLDataCommand,
    BulkSyncWorkerCMLDataCommandHandler,
    BulkSyncWorkerEC2StatusCommand,
    BulkSyncWorkerEC2StatusCommandHandler,
    CollectWorkerCloudWatchMetricsCommand,
    CollectWorkerCloudWatchMetricsCommandHandler,
    CreateCMLWorkerCommand,
    CreateCMLWorkerCommandHandler,
    DeleteCMLWorkerCommand,
    DeleteCMLWorkerCommandHandler,
    DeregisterCMLWorkerLicenseCommand,
    DeregisterCMLWorkerLicenseCommandHandler,
    DetectWorkerIdleCommand,
    DetectWorkerIdleCommandHandler,
    DisableIdleDetectionCommand,
    DisableIdleDetectionCommandHandler,
    EnableIdleDetectionCommand,
    EnableIdleDetectionCommandHandler,
    EnableWorkerDetailedMonitoringCommand,
    EnableWorkerDetailedMonitoringCommandHandler,
    ImportCMLWorkerCommand,
    ImportCMLWorkerCommandHandler,
    PauseWorkerCommand,
    PauseWorkerCommandHandler,
    RefreshWorkerLabsCommand,
    RefreshWorkerLabsCommandHandler,
    RefreshWorkerMetricsCommand,
    RefreshWorkerMetricsCommandHandler,
    RegisterCMLWorkerLicenseCommand,
    RegisterCMLWorkerLicenseCommandHandler,
    RequestWorkerDataRefreshCommand,
    RequestWorkerDataRefreshCommandHandler,
    StartCMLWorkerCommand,
    StartCMLWorkerCommandHandler,
    StopCMLWorkerCommand,
    StopCMLWorkerCommandHandler,
    SyncWorkerCMLDataCommand,
    SyncWorkerCMLDataCommandHandler,
    SyncWorkerEC2StatusCommand,
    SyncWorkerEC2StatusCommandHandler,
    TerminateCMLWorkerCommand,
    TerminateCMLWorkerCommandHandler,
    UpdateCMLWorkerStatusCommand,
    UpdateCMLWorkerStatusCommandHandler,
    UpdateCMLWorkerTagsCommand,
    UpdateCMLWorkerTagsCommandHandler,
    UpdateWorkerActivityCommand,
    UpdateWorkerActivityCommandHandler,
)

__all__ = [
    # Base class
    "CommandHandlerBase",
    # Lab commands
    "ControlLabCommand",
    "ControlLabCommandHandler",
    "DeleteLabCommand",
    "DeleteLabCommandHandler",
    "DownloadLabCommand",
    "DownloadLabCommandHandler",
    "ImportLabCommand",
    "ImportLabCommandHandler",
    "LabAction",
    # Settings commands
    "UpdateSystemSettingsCommand",
    "UpdateSystemSettingsCommandHandler",
    # Task commands
    "CreateTaskCommand",
    "CreateTaskCommandHandler",
    "DeleteTaskCommand",
    "DeleteTaskCommandHandler",
    "UpdateTaskCommand",
    "UpdateTaskCommandHandler",
    # Worker commands
    "BulkImportCMLWorkersCommand",
    "BulkImportCMLWorkersCommandHandler",
    "BulkImportResult",
    "BulkSyncWorkerCMLDataCommand",
    "BulkSyncWorkerCMLDataCommandHandler",
    "BulkSyncWorkerEC2StatusCommand",
    "BulkSyncWorkerEC2StatusCommandHandler",
    "BulkSyncResult",
    "CollectWorkerCloudWatchMetricsCommand",
    "CollectWorkerCloudWatchMetricsCommandHandler",
    "CreateCMLWorkerCommand",
    "CreateCMLWorkerCommandHandler",
    "DeleteCMLWorkerCommand",
    "DeleteCMLWorkerCommandHandler",
    "DeregisterCMLWorkerLicenseCommand",
    "DeregisterCMLWorkerLicenseCommandHandler",
    "DetectWorkerIdleCommand",
    "DetectWorkerIdleCommandHandler",
    "DisableIdleDetectionCommand",
    "DisableIdleDetectionCommandHandler",
    "EnableIdleDetectionCommand",
    "EnableIdleDetectionCommandHandler",
    "EnableWorkerDetailedMonitoringCommand",
    "EnableWorkerDetailedMonitoringCommandHandler",
    "ImportCMLWorkerCommand",
    "ImportCMLWorkerCommandHandler",
    "PauseWorkerCommand",
    "PauseWorkerCommandHandler",
    "RefreshWorkerLabsCommand",
    "RefreshWorkerLabsCommandHandler",
    "RefreshWorkerMetricsCommand",
    "RefreshWorkerMetricsCommandHandler",
    "RegisterCMLWorkerLicenseCommand",
    "RegisterCMLWorkerLicenseCommandHandler",
    "RequestWorkerDataRefreshCommand",
    "RequestWorkerDataRefreshCommandHandler",
    "StartCMLWorkerCommand",
    "StartCMLWorkerCommandHandler",
    "StopCMLWorkerCommand",
    "StopCMLWorkerCommandHandler",
    "SyncWorkerCMLDataCommand",
    "SyncWorkerCMLDataCommandHandler",
    "SyncWorkerEC2StatusCommand",
    "SyncWorkerEC2StatusCommandHandler",
    "TerminateCMLWorkerCommand",
    "TerminateCMLWorkerCommandHandler",
    "UpdateCMLWorkerStatusCommand",
    "UpdateCMLWorkerStatusCommandHandler",
    "UpdateCMLWorkerTagsCommand",
    "UpdateCMLWorkerTagsCommandHandler",
    "UpdateSystemSettingsCommand",
    "UpdateSystemSettingsCommandHandler",
    "UpdateTaskCommand",
    "UpdateTaskCommandHandler",
    "UpdateWorkerActivityCommand",
    "UpdateWorkerActivityCommandHandler",
]
